/**
 * Label dokumen cetak (DOCX dan Excel), per bahasa.
 *
 * Yang berpindah ke sini hanya KATA-KATANYA. Bentuk tabel, urutan kolom, dan
 * susunan bagian A–J tidak berubah sedikit pun: template adalah data, dan
 * template ITTS tetap tabel mingguan 7 kolom di kedua bahasa (docs/11 §7).
 *
 * Berkas berbahasa Inggris adalah terjemahan resmi yang diterbitkan
 * berdampingan. **Naskah yang sah tetap yang berbahasa Indonesia**, dan
 * halaman pengesahannya menyatakan itu di kaki halaman — untuk keperluan
 * akreditasi, yang diserahkan tetap berkas Indonesia.
 */

import type { Bahasa } from "@/kamus";

export const labelDokumenId = {
  belumAdaButir: "(belum ada butir)",
  belumAdaPustaka: "(belum ada pustaka)",
  belumAdaTopik: "(belum ada topik)",
  belumDiisi: "(belum diisi)",
  gambarTerlampir: "- Gambar Terlampir -",
  ambangBatasKelulusan: "AMBANG BATAS KELULUSAN",
  analisisPembelajaran: "ANALISIS PEMBELAJARAN",
  aktivitas: "Aktivitas:",
  alokasiWaktu: "Alokasi Waktu",
  ambangBatasKelulusanMk: "Ambang Batas Kelulusan MK\t: ",
  ambangBatasKelulusanMahasiswa: "Ambang Batas Kelulusan Mahasiswa\t: ",
  b1CapaianPembelajaranLulusanCpl:
    "B.1  Capaian Pembelajaran Lulusan (CPL) Program Studi yang Terkait dengan Mata Kuliah",
  b2CapaianPembelajaranMataKuliah: "B.2  Capaian Pembelajaran Mata Kuliah (CPMK)",
  b3SubCapaianPembelajaranMata: "B.3  Sub Capaian Pembelajaran Mata Kuliah (Sub-CPMK)",
  bentuk: "Bentuk",
  bobot: "Bobot",
  bobot2: "Bobot (%)",
  bobot3: "Bobot\t: ",
  butir: "Butir",
  capaianPembelajaran: "CAPAIAN PEMBELAJARAN",
  cpl: "CPL",
  cpmk: "CPMK",
  deskripsiMataKuliah: "DESKRIPSI MATA KULIAH",
  detailTugasProyek: "DETAIL TUGAS / PROYEK",
  deskripsiAktivitas: "Deskripsi Aktivitas",
  deskripsiPerubahan: "Deskripsi Perubahan",
  deskripsiTugas: "Deskripsi Tugas",
  disetujuiOleh: "Disetujui oleh,",
  dokumenIniDicetakDariSalinanResmi: "Dokumen ini dicetak dari salinan resmi versi ",
  dosen: "Dosen: ",
  evaluasiPembelajaran: "EVALUASI PEMBELAJARAN",
  formatDanLuaran: "Format dan Luaran",
  halamanPengesahan: "HALAMAN PENGESAHAN",
  historiRevisi: "HISTORI REVISI",
  institutTeknologiTangerangSelatan: "INSTITUT TEKNOLOGI TANGERANG SELATAN",
  indikator: "Indikator",
  indikatorSoal: "Indikator soal",
  indikatorKriteriaDanBobotPenilaian: "Indikator, Kriteria, dan Bobot Penilaian",
  jenisPenilaianDanSistemPenilaian: "Jenis Penilaian dan Sistem Penilaian",
  jenisTugasProyek: "Jenis Tugas / Proyek\t: ",
  keterangan: "KETERANGAN",
  kodeDokumenFormRpkps: "KODE DOKUMEN : FORM RPKPS",
  kodeMkSks: "KODE MK / SKS\t: ",
  kepalaPenjaminanMutuInternal: "Kepala Penjaminan Mutu Internal",
  ketentuanLainnya: "Ketentuan Lainnya",
  ketuaProgramStudi: "Ketua Program Studi",
  kodeMk: "Kode MK",
  kodeMataKuliah: "Kode Mata Kuliah\t: ",
  koordinatorMataKuliah: "Koordinator Mata Kuliah",
  koordinatorMataKuliah2: "Koordinator Mata Kuliah\t: ",
  lampiranKisiKisiUjian: "LAMPIRAN — KISI-KISI UJIAN",
  level: "Level",
  linimasaProyekTugas: "Linimasa Proyek / Tugas",
  mkPrasyarat: "MK PRASYARAT\t: ",
  mahasiswa: "Mahasiswa: ",
  metodePembelajaran: "Metode Pembelajaran:",
  metodeDanAktivitasPembelajaran: "Metode dan Aktivitas Pembelajaran",
  mingguKe: "Minggu ke",
  namaMataKuliah: "NAMA MATA KULIAH\t: ",
  nidnNipNik: "NIDN / NIP / NIK",
  nilaiAngka: "NILAI ANGKA",
  nilaiHuruf: "NILAI HURUF",
  namaDosen: "Nama Dosen",
  namaMataKuliah2: "Nama Mata Kuliah\t: ",
  no: "No.",
  noRevisi: "No. Revisi",
  nomorTugasProyek: "Nomor Tugas / Proyek\t: ",
  penilaianAkhir: "PENILAIAN AKHIR :",
  penilaian: "Penilaian",
  penilaian2: "Penilaian:",
  referensiDanSumberPembelajaran: "REFERENSI DAN SUMBER PEMBELAJARAN",
  rencanaPembelajaranMingguan: "RENCANA PEMBELAJARAN MINGGUAN",
  rencanaProgramDanKegiatanPembelaja:
    "RENCANA PROGRAM DAN KEGIATAN PEMBELAJARAN SEMESTER (RPKPS)",
  rentangSkor: "RENTANG SKOR",
  referensi: "Referensi",
  semester: "SEMESTER\t: ",
  statusMatakuliah: "STATUS MATAKULIAH\t: ",
  subCpmk: "SUB-CPMK",
  sistemPenilaian: "Sistem Penilaian:",
  skor: "Skor",
  subCpmk2: "Sub-CPMK",
  subCpmkTerkait: "Sub-CPMK Terkait\t: ",
  subCapaianPembelajaranMataKuliahSu: "Sub-Capaian Pembelajaran Mata Kuliah (Sub-CPMK)",
  subtopik: "Subtopik:",
  topikPembelajaran: "TOPIK PEMBELAJARAN",
  tabelDistribusiPenilaianCapaianPem: "Tabel: Distribusi Penilaian Capaian Pembelajaran",
  tahapan: "Tahapan",
  tandaTangan: "Tanda Tangan",
  tanggal: "Tanggal :",
  tanggalBerlaku: "Tanggal Berlaku",
  telahDiperiksaDanDinyatakanSesuaiD:
    "Telah diperiksa dan dinyatakan sesuai dengan standar ITTS",
  timDosenPengampu: "Tim Dosen Pengampu\t:",
  tingkatKkni6: "Tingkat KKNI: 6",
  topikSubtopik: "Topik & Subtopik",
  topik: "Topik: ",
  total: "Total",
  tugasPekerjaanTerstrukturPt: "Tugas / Pekerjaan Terstruktur (PT):",
  uraianTugas: "Uraian Tugas",
  aNTimPenyusunRpkps: "a.n Tim penyusun RPKPS",

  aturanKehadiran:
    "Kehadiran tepat waktu dalam perkuliahan adalah wajib. Mahasiswa akan dianggap tidak hadir apabila datang melebihi waktu yang telah ditentukan.",
  aturanMinimalHadir:
    "Mengikuti {pertemuan} kali pertemuan perkuliahan adalah wajib. Mahasiswa harus hadir minimal {minimal} dari {pertemuan} pertemuan untuk dapat mengikuti ujian akhir.",
  nilaiAkhirDitentukan: "Nilai akhir ditentukan berdasarkan komponen berikut:",
  totalSkorKisi: "Total skor {skor}",
  durasiKisi: " · durasi {menit} menit",
  sidikDokumen: ". Sidik dokumen: {sidik}",


  /**
   * Label berkas Excel.
   *
   * PENGENAL TIDAK ADA DI SINI, dan itu disengaja. Judul kolom "NIM", "Nama",
   * "Angkatan", nama lembar "Nilai"/"Petunjuk"/"Butir UTS", serta nama lembar
   * templat kurikulum adalah PENGENAL yang dicocokkan saat berkas diunggah
   * kembali. Menerjemahkannya membuat berkas yang diunduh dalam bahasa Inggris
   * tidak dapat diunggah kembali — dan gagalnya senyap: pembaca hanya melaporkan
   * "kolom tidak ditemukan" (docs/11 §7). Yang diterjemahkan hanya baris judul
   * lembar Petunjuk dan kalimat-kalimat penjelasnya, yang tidak pernah dibaca.
   */
  excel: {
    kode: "Kode",
    asesmen: "Asesmen",
    masukKomponen: "Masuk komponen",
    bobotPersen: "Bobot (%)",
    subDitagih: "Sub-CPMK yang ditagih",
    tanpaKomponen: "tanpa komponen",
    isiSkor: "Isi skor 0–100 pada lembar Nilai. Sel yang dikosongkan berarti belum dinilai.",
    janganUbahJudul:
      "Jangan mengubah judul kolom — kode itulah yang menyambungkan nilai ke rencana.",
    pengenalTetapIndonesia:
      "Judul kolom dan nama lembar sengaja tetap berbahasa Indonesia: itulah pengenal yang dibaca saat berkas ini diunggah kembali.",
    catatanAsesmen: "{nama} · {bobot}% · {komponen}",
    catatanButir: "{kode} · skor maksimum {skor}",
    kakiHalaman: "{prodi} - ITTS    Tahun Akademik : {semester} {tahun}",
    semesterGanjil: "Ganjil",
    semesterGenap: "Genap",
    semesterAntara: "Antara",
    templatKurikulum: [
      "Template Impor Kurikulum — RPKPS ITTS",
      "",
      "Nama lembar dan judul kolom adalah PENGENAL yang dibaca saat berkas ini",
      "diunggah kembali. Jangan mengganti atau menerjemahkannya — berkas yang",
      "judul kolomnya diubah tidak akan dapat diimpor.",
      "",
      "Isi lima lembar berikut sesuai buku kurikulum program studi.",
      "Baris contoh berwarna abu-abu boleh langsung ditimpa atau dihapus.",
      "",
      "1. Profil Lulusan — peran yang dijanjikan prodi kepada lulusannya.",
      "   Kode PL harus unik, mis. PL1. Lembar ini boleh dikosongkan, tetapi",
      "   tanpa itu CPL tidak dapat ditelusuri kembali ke janji program studi.",
      "   Setiap profil WAJIB ditopang minimal satu CPL — profil yang tidak",
      "   ditopang CPL mana pun akan ditolak.",
      "",
      "2. CPL — Capaian Pembelajaran Lulusan program studi.",
      "   Kode CPL harus unik, mis. CPL06.",
      "   Kolom Kode PL diisi profil lulusan yang ditopang CPL ini, dipisah koma.",
      "",
      "3. Mata Kuliah — daftar mata kuliah beserta beban sks.",
      "   sks dipecah TEORI dan PRAKTIK. Totalnya sama, tetapi beban terjadwal",
      "   berbeda jauh: 3 sks teori butuh 150 menit tatap muka, sedangkan",
      "   2 teori + 1 praktik butuh 200 menit karena praktikum memakai slot lab.",
      "   Kolom Kode CPL diisi kode CPL yang dibebankan, dipisah koma.",
      "",
      "4. CPMK — Capaian Pembelajaran Mata Kuliah.",
      "   Setiap CPMK harus menjabarkan minimal satu CPL yang dibebankan pada",
      "   mata kuliahnya. CPL yang dibebankan tetapi tidak dijabarkan CPMK mana pun",
      "   akan ditolak — CPL seperti itu tidak akan pernah dinilai.",
      "",
      "5. Sub-CPMK — tahapan belajar, umumnya satu per pertemuan.",
      "   Isi Kode MK DAN Kode CPMK induknya. Kode CPMK hanya unik di dalam satu",
      "   mata kuliah, jadi \"CPMK01\" saja tidak menunjukkan induk yang mana bila",
      "   dipakai beberapa mata kuliah sekaligus.",
      "   Level Bloom Sub-CPMK tidak boleh melampaui CPMK induknya.",
      "",
      "Level Bloom yang dikenali:",
      "   Kognitif   C1 Mengingat · C2 Memahami · C3 Menerapkan",
      "              C4 Menganalisis · C5 Mengevaluasi · C6 Mencipta",
      "   Afektif    A1–A5      Psikomotor  P1–P5",
      "   Kolom ini boleh dikosongkan; sistem akan menebaknya dari kata kerja.",
      "",
      "Hindari kata yang tidak dapat diamati seperti \"memahami\" atau \"mengetahui\"",
      "pada rumusan Sub-CPMK — keduanya tidak dapat dijadikan dasar penilaian.",
    ],
  },
    lkps: {
      lembarCapaian: "Capaian CPL",
      lembarTren: "Tren",
      lembarSebaran: "Sebaran Kelas",
      lembarRincian: "Rincian",
      deskripsi: "Deskripsi",
      rerataTertimbang: "Rerata (tertimbang sks)",
      mahasiswaLulusPersen: "Mahasiswa lulus (%)",
      status: "Status",
      mkTerukur: "MK terukur",
      kelasTercapaiTerukur: "Kelas tercapai / terukur",
      mahasiswaTerukur: "Mahasiswa terukur",
      mataKuliah: "Mata Kuliah",
      tahunAkademik: "Tahun Akademik",
      kelasTertinggi: "Kelas tertinggi",
      kelasTerendah: "Kelas terendah",
      selisihPoin: "Selisih (poin)",
      kelas: "Kelas",
      rerata: "Rerata",
      lulusPersen: "Lulus (%)",
      tercapai: "Tercapai",
      catatan: "Catatan",
      cakupan: "Cakupan",
      angkaSelPersen: "Angka pada sel adalah persen mahasiswa yang lulus CPL tersebut.",
      tanpaSelisih: "Tidak ada selisih antar kelas yang mencolok.",
      selisihMenunjukPelaksanaan:
        "Rencana yang sama dengan hasil jauh berbeda menunjuk pelaksanaan, bukan rancangan.",
    },


    portofolio: {
      akarMasalah: "Akar Masalah",
      asesmen: "Asesmen",
      asesmenYangMenyusunCapaian: "Asesmen yang menyusun capaian",
      belumDiisi: "Belum diisi.",
      bobot: "Bobot",
      butir: "Butir",
      capaianPerButir: "CAPAIAN PER BUTIR",
      catatanProsesPembelajaran: "CATATAN PROSES PEMBELAJARAN",
      cplTercapai: "CPL tercapai",
      cpmk: "CPMK",
      cpmkTercapai: "CPMK tercapai",
      capaian: "Capaian",
      dosenPengampu: "Dosen Pengampu",
      evaluasiBelumDitutup:
        "Evaluasi belum ditutup. Angka pada dokumen ini masih dapat berubah dan belum menjadi catatan resmi.",
      identitas: "IDENTITAS",
      jumlahPeserta: "Jumlah Peserta",
      kelas: "Kelas",
      kelengkapanNilai: "Kelengkapan nilai",
      kode: "Kode",
      komponen: "Komponen",
      mahasiswaLulus: "Mahasiswa Lulus",
      mataKuliah: "Mata Kuliah",
      pengesahan: "PENGESAHAN",
      portofolioMataKuliah: "PORTOFOLIO MATA KULIAH",
      penanggungJawabBerlaku: "Penanggung Jawab / Berlaku",
      pita: "Pita",
      ringkasanKetercapaian: "RINGKASAN KETERCAPAIAN",
      rerata: "Rerata",
      rerataNilaiAkhir: "Rerata nilai akhir",
      statusDokumen: "STATUS DOKUMEN",
      sidikDihitungSha256:
        "Sidik dihitung dengan SHA-256 atas seluruh isi evaluasi. Nilai mahasiswa boleh berubah setelah remedial; salinan beku yang menghasilkan sidik ini tidak.",
      sidikDokumen: "Sidik dokumen: ",
      status: "Status",
      subCpmk: "Sub-CPMK",
      temuanDanRtl: "TEMUAN DAN RENCANA TINDAK LANJUT",
      tahunAkademik: "Tahun Akademik",
      tanpaTindakLanjut:
        "Tidak ada CPMK yang berada di bawah ambang ketercapaian, sehingga tidak ada tindak lanjut yang diwajibkan pada semester ini.",
      tindakan: "Tindakan",
      verifikasiTindakLanjut: "Verifikasi tindak lanjut",
    },

  /** Hanya dicetak pada berkas berbahasa Inggris. */
  naskahSahIndonesia: "",

  jenisPustaka: {
    UTAMA: "Sumber Utama",
    PENDUKUNG: "Sumber Pendukung",
    DARING: "Sumber Belajar Daring",
    TOOLS: "Perangkat Lunak dan Tools Praktikum",
  } as Record<string, string>,

  bentukSoal: {
    PILIHAN_GANDA: "Pilihan ganda",
    ESAI: "Esai",
    URAIAN_SINGKAT: "Uraian singkat",
    STUDI_KASUS: "Studi kasus",
    PRAKTIK: "Praktik",
    PROYEK: "Proyek",
    LISAN: "Lisan",
  } as Record<string, string>,

  keteranganNilai: {
    sangatBaik: "Sangat Baik",
    baik: "Baik",
    memuaskan: "Memuaskan",
    kurangMemuaskan: "Kurang Memuaskan",
    sangatTidakMemuaskan: "Sangat Tidak Memuaskan",
  },
} as const;

/**
 * Bentuk tabel label: kunci dan susunan sama, nilainya `string` biasa.
 *
 * `as const` di atas membuat tiap label bertipe literal dirinya sendiri —
 * berguna untuk menguncikan daftar kunci, tetapi akan menolak terjemahan apa
 * pun kalau dipakai langsung sebagai tipe `labelDokumenEn`. Pemetaan ini
 * melebarkan nilainya tanpa melepas jaminan yang penting: kunci yang sama, dan
 * bentuk yang sama (larik tetap larik, peta tetap peta).
 */
type LebarkanLabel<T> = T extends readonly string[]
  ? string[]
  : T extends Record<string, string>
    ? Record<string, string>
    : T extends object
      ? { [M in keyof T]: LebarkanLabel<T[M]> }
      : string;

export type LabelDokumen = LebarkanLabel<typeof labelDokumenId>;

export const labelDokumenEn: LabelDokumen = {
  belumAdaButir: "(no items yet)",
  belumAdaPustaka: "(no readings yet)",
  belumAdaTopik: "(no topic yet)",
  belumDiisi: "(not filled in)",
  gambarTerlampir: "- Figure attached -",
  ambangBatasKelulusan: "PASSING THRESHOLD",
  analisisPembelajaran: "LEARNING ANALYSIS",
  aktivitas: "Activities:",
  alokasiWaktu: "Time Allocation",
  ambangBatasKelulusanMk: "Course attainment threshold\t: ",
  ambangBatasKelulusanMahasiswa: "Student passing threshold\t: ",
  b1CapaianPembelajaranLulusanCpl:
    "B.1  Programme Learning Outcomes (CPL) Related to This Course",
  b2CapaianPembelajaranMataKuliah: "B.2  Course Learning Outcomes (CPMK)",
  b3SubCapaianPembelajaranMata: "B.3  Sub Course Learning Outcomes (Sub-CPMK)",
  bentuk: "Form",
  bobot: "Weight",
  bobot2: "Weight (%)",
  bobot3: "Weight\t: ",
  butir: "Items",
  capaianPembelajaran: "LEARNING OUTCOMES",
  cpl: "CPL",
  cpmk: "CPMK",
  deskripsiMataKuliah: "COURSE DESCRIPTION",
  detailTugasProyek: "ASSIGNMENT / PROJECT DETAIL",
  deskripsiAktivitas: "Activity Description",
  deskripsiPerubahan: "Description of Change",
  deskripsiTugas: "Assignment Description",
  disetujuiOleh: "Approved by,",
  dokumenIniDicetakDariSalinanResmi: "This document is printed from the official copy, version ",
  dosen: "Lecturer: ",
  evaluasiPembelajaran: "LEARNING ASSESSMENT",
  formatDanLuaran: "Format and Deliverable",
  halamanPengesahan: "APPROVAL PAGE",
  historiRevisi: "REVISION HISTORY",
  institutTeknologiTangerangSelatan: "INSTITUT TEKNOLOGI TANGERANG SELATAN",
  indikator: "Indicator",
  indikatorSoal: "Item indicator",
  indikatorKriteriaDanBobotPenilaian: "Indicators, Criteria, and Assessment Weights",
  jenisPenilaianDanSistemPenilaian: "Assessment Form and Assessment System",
  jenisTugasProyek: "Assignment / Project Type\t: ",
  keterangan: "REMARKS",
  kodeDokumenFormRpkps: "DOCUMENT CODE : FORM RPKPS",
  kodeMkSks: "COURSE CODE / CREDITS\t: ",
  kepalaPenjaminanMutuInternal: "Head of Internal Quality Assurance",
  ketentuanLainnya: "Other Provisions",
  ketuaProgramStudi: "Head of Study Programme",
  kodeMk: "Course Code",
  kodeMataKuliah: "Course Code\t: ",
  koordinatorMataKuliah: "Course Coordinator",
  koordinatorMataKuliah2: "Course Coordinator\t: ",
  lampiranKisiKisiUjian: "APPENDIX — EXAM BLUEPRINT",
  level: "Level",
  linimasaProyekTugas: "Project / Assignment Timeline",
  mkPrasyarat: "PREREQUISITE\t: ",
  mahasiswa: "Students: ",
  metodePembelajaran: "Teaching method:",
  metodeDanAktivitasPembelajaran: "Teaching Method and Learning Activities",
  mingguKe: "Week",
  namaMataKuliah: "COURSE NAME\t: ",
  nidnNipNik: "NIDN / NIP / NIK",
  nilaiAngka: "GRADE POINT",
  nilaiHuruf: "LETTER GRADE",
  namaDosen: "Lecturer Name",
  namaMataKuliah2: "Course Name\t: ",
  no: "No.",
  noRevisi: "Revision No.",
  nomorTugasProyek: "Assignment / Project No.\t: ",
  penilaianAkhir: "FINAL ASSESSMENT :",
  penilaian: "Assessment",
  penilaian2: "Assessment:",
  referensiDanSumberPembelajaran: "REFERENCES AND LEARNING RESOURCES",
  rencanaPembelajaranMingguan: "WEEKLY LEARNING PLAN",
  rencanaProgramDanKegiatanPembelaja:
    "SEMESTER LEARNING PROGRAMME AND ACTIVITY PLAN (RPKPS)",
  rentangSkor: "SCORE RANGE",
  referensi: "References",
  semester: "SEMESTER\t: ",
  statusMatakuliah: "COURSE STATUS\t: ",
  subCpmk: "SUB-CPMK",
  sistemPenilaian: "Assessment system:",
  skor: "Score",
  subCpmk2: "Sub-CPMK",
  subCpmkTerkait: "Related Sub-CPMK\t: ",
  subCapaianPembelajaranMataKuliahSu: "Sub Course Learning Outcomes (Sub-CPMK)",
  subtopik: "Subtopics:",
  topikPembelajaran: "LEARNING TOPICS",
  tabelDistribusiPenilaianCapaianPem: "Table: Assessment Distribution Across Learning Outcomes",
  tahapan: "Stage",
  tandaTangan: "Signature",
  tanggal: "Date :",
  tanggalBerlaku: "Effective Date",
  telahDiperiksaDanDinyatakanSesuaiD:
    "Reviewed and declared compliant with ITTS standards",
  timDosenPengampu: "Teaching Team\t:",
  tingkatKkni6: "KKNI level: 6",
  topikSubtopik: "Topic & Subtopics",
  topik: "Topic: ",
  total: "Total",
  tugasPekerjaanTerstrukturPt: "Structured assignment (PT):",
  uraianTugas: "Assignment Brief",
  aNTimPenyusunRpkps: "on behalf of the RPKPS writing team",

  aturanKehadiran:
    "Punctual attendance is compulsory. A student arriving later than the stated time is recorded as absent.",
  aturanMinimalHadir:
    "Attending {pertemuan} teaching sessions is compulsory. A student must attend at least {minimal} of the {pertemuan} sessions to sit the final exam.",
  nilaiAkhirDitentukan: "The final grade is determined by the following components:",
  totalSkorKisi: "Total score {skor}",
  durasiKisi: " · {menit} minutes",
  sidikDokumen: ". Document fingerprint: {sidik}",


  excel: {
    kode: "Code",
    asesmen: "Assessment",
    masukKomponen: "Component",
    bobotPersen: "Weight (%)",
    subDitagih: "Sub-CPMK assessed",
    tanpaKomponen: "no component",
    isiSkor:
      "Enter scores 0–100 on the Nilai sheet. An empty cell means not yet marked.",
    janganUbahJudul:
      "Do not change the column headings — those codes are what link the scores back to the plan.",
    pengenalTetapIndonesia:
      "Column headings and sheet names deliberately stay in Indonesian: they are the identifiers read when this file is uploaded again.",
    catatanAsesmen: "{nama} · {bobot}% · {komponen}",
    catatanButir: "{kode} · max score {skor}",
    kakiHalaman: "{prodi} - ITTS    Academic Year : {semester} {tahun}",
    semesterGanjil: "Odd",
    semesterGenap: "Even",
    semesterAntara: "Short",
    templatKurikulum: [
      "Curriculum Import Template — RPKPS ITTS",
      "",
      "Sheet names and column headings are IDENTIFIERS read when this file is",
      "uploaded again. Do not rename or translate them — a file whose headings",
      "were changed cannot be imported.",
      "",
      "Fill in the five sheets below from the study programme's curriculum book.",
      "The grey example rows may be overwritten or deleted.",
      "",
      "1. Profil Lulusan — the roles the programme promises its graduates.",
      "   Each Kode PL must be unique, e.g. PL1. This sheet may be left empty, but",
      "   without it a CPL cannot be traced back to what the programme promises.",
      "   Every profile MUST be supported by at least one CPL — a profile supported",
      "   by none will be rejected.",
      "",
      "2. CPL — programme learning outcomes.",
      "   Each Kode CPL must be unique, e.g. CPL06.",
      "   The Kode PL column lists the graduate profiles this CPL supports, comma-separated.",
      "",
      "3. Mata Kuliah — the courses and their credit load.",
      "   Credits are split into TEORI (theory) and PRAKTIK (practicum). The total is",
      "   the same, but the scheduled load differs sharply: 3 theory credits need 150",
      "   contact minutes, while 2 theory + 1 practicum needs 200 because the",
      "   practicum occupies a lab slot.",
      "   The Kode CPL column lists the CPLs assigned to the course, comma-separated.",
      "",
      "4. CPMK — course learning outcomes.",
      "   Every CPMK must elaborate at least one CPL assigned to its course. A CPL",
      "   assigned but elaborated by no CPMK is rejected — it would never be assessed.",
      "",
      "5. Sub-CPMK — learning stages, usually one per meeting.",
      "   Fill in BOTH Kode MK and the parent Kode CPMK. A CPMK code is unique only",
      "   within one course, so \"CPMK01\" alone does not say which parent is meant",
      "   when several courses use it.",
      "   A Sub-CPMK's Bloom level must not exceed that of its parent CPMK.",
      "",
      "Recognised Bloom levels:",
      "   Cognitive   C1 Remember · C2 Understand · C3 Apply",
      "               C4 Analyse · C5 Evaluate · C6 Create",
      "   Affective   A1–A5      Psychomotor  P1–P5",
      "   This column may be left empty; the system infers it from the verb.",
      "",
      "Avoid verbs that cannot be observed, such as \"understand\" or \"know\", in a",
      "Sub-CPMK statement — neither can serve as a basis for assessment.",
    ],
  },
    lkps: {
      lembarCapaian: "CPL Attainment",
      lembarTren: "Trend",
      lembarSebaran: "Class Spread",
      lembarRincian: "Detail",
      deskripsi: "Description",
      rerataTertimbang: "Mean (credit-weighted)",
      mahasiswaLulusPersen: "Students passing (%)",
      status: "Status",
      mkTerukur: "Courses measured",
      kelasTercapaiTerukur: "Classes achieved / measured",
      mahasiswaTerukur: "Students measured",
      mataKuliah: "Course",
      tahunAkademik: "Academic Year",
      kelasTertinggi: "Highest class",
      kelasTerendah: "Lowest class",
      selisihPoin: "Gap (points)",
      kelas: "Class",
      rerata: "Mean",
      lulusPersen: "Passing (%)",
      tercapai: "Achieved",
      catatan: "Note",
      cakupan: "Coverage",
      angkaSelPersen: "Each cell is the percentage of students who passed that CPL.",
      tanpaSelisih: "No striking gap between classes.",
      selisihMenunjukPelaksanaan:
        "The same plan with very different results points at delivery, not at the design.",
    },


    portofolio: {
      akarMasalah: "Root Cause",
      asesmen: "Assessment",
      asesmenYangMenyusunCapaian: "Assessments that make up the attainment",
      belumDiisi: "Not filled in.",
      bobot: "Weight",
      butir: "Items",
      capaianPerButir: "PER-ITEM ATTAINMENT",
      catatanProsesPembelajaran: "TEACHING PROCESS NOTES",
      cplTercapai: "CPLs achieved",
      cpmk: "CPMK",
      cpmkTercapai: "CPMKs achieved",
      capaian: "Attainment",
      dosenPengampu: "Teaching Staff",
      evaluasiBelumDitutup:
        "The evaluation is not closed. Figures in this document may still change and are not yet an official record.",
      identitas: "IDENTITY",
      jumlahPeserta: "Number of Students",
      kelas: "Class",
      kelengkapanNilai: "Score completeness",
      kode: "Code",
      komponen: "Component",
      mahasiswaLulus: "Students Passing",
      mataKuliah: "Course",
      pengesahan: "APPROVAL",
      portofolioMataKuliah: "COURSE PORTFOLIO",
      penanggungJawabBerlaku: "Responsible / Effective",
      pita: "Band",
      ringkasanKetercapaian: "ATTAINMENT SUMMARY",
      rerata: "Mean",
      rerataNilaiAkhir: "Mean final grade",
      statusDokumen: "DOCUMENT STATUS",
      sidikDihitungSha256:
        "The fingerprint is a SHA-256 over the whole evaluation. Student marks may change after a resit; the frozen copy that produced this fingerprint does not.",
      sidikDokumen: "Document fingerprint: ",
      status: "Status",
      subCpmk: "Sub-CPMK",
      temuanDanRtl: "FINDINGS AND FOLLOW-UP PLAN",
      tahunAkademik: "Academic Year",
      tanpaTindakLanjut:
        "No CPMK fell below the attainment threshold, so no follow-up is required this semester.",
      tindakan: "Action",
      verifikasiTindakLanjut: "Follow-up verification",
    },

  naskahSahIndonesia:
    "This is an English translation. The Indonesian version is the official, signed document.",

  jenisPustaka: {
    UTAMA: "Primary Sources",
    PENDUKUNG: "Supporting Sources",
    DARING: "Online Learning Resources",
    TOOLS: "Software and Lab Tools",
  },

  bentukSoal: {
    PILIHAN_GANDA: "Multiple choice",
    ESAI: "Essay",
    URAIAN_SINGKAT: "Short answer",
    STUDI_KASUS: "Case study",
    PRAKTIK: "Practical",
    PROYEK: "Project",
    LISAN: "Oral",
  },

  keteranganNilai: {
    sangatBaik: "Excellent",
    baik: "Good",
    memuaskan: "Satisfactory",
    kurangMemuaskan: "Unsatisfactory",
    sangatTidakMemuaskan: "Very unsatisfactory",
  },
};

export function labelDokumen(bahasa: Bahasa): LabelDokumen {
  return bahasa === "en" ? labelDokumenEn : (labelDokumenId as unknown as LabelDokumen);
}
